name: check24 pull

on:
  workflow_dispatch:
  push:
    paths:
    - ".github/workflows/check24-pull.yml"
  schedule: 
    - cron:  '* * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: curl "https://pub-api.handytarife.check24.de/v1/desktop/result/collection/sim?bullet_sort_split=4&network_tmobile=yes&network_vodafone=yes&network_o2=yes&data_included=0&minutes_included=all&rnp=egal&tariff_type=all&select_contract=-24&data_speed=0&maximum_effective_price=egal&provider_restriction=&5g=all&young_tariff=all&tariff_activation_date=no&hardware_nature=40&with_data_tariffs=all&only_bookable_tariffs=no&fixed_traffic_automatic=egal&sms_included=all&request_extended_advertisements=true&_EXP0013=b" | jq . > rows.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        #git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "update rows.json" || exit 0
        git push
