name: Rows changed

on:
  push:
    paths:
    - '.github/workflows/on-change.yaml'
    - 'rows.json'
    - 'json2csv.py'

jobs:
  adjusted:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.PAT}}
    - run: pip install pandas
    - run: python json2csv.py --check24all
    - run: python json2csv.py --check24core
    - run: python json2csv.py --check24adjusted
    - run: git status
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -a --allow-empty-message -m '' || exit 0
        git pull && git push
